micronaut:
  server:
    port: 8081
  application:
    name: candleAnalyzer
datasources:
  default:
    driver-class-name: org.postgresql.Driver
    db-type: postgres
netty:
  default:
    allocator:
      max-order: 3
